---
title: "John’s Py Notes"
author: "John Van Camp"
date: "1/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jvctools); defl()
```

```{r start py w/reticulate}
require(reticulate)
use_python(python='/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6')
sys<-import('sys')
py<-import_builtins()
py_run_string("sys.path.append('/Users/John/Documents/R/Twitter')")
```

```{r get version}
py_discover_config()     # get the version
py<-import_builtins()    # get installed packages
```

```{r packages}
py_install("matplotlib") # install a package
keys<-import('keys')     # use a package
py_module_available()    # Check if a Python module is available on this system.

# use "$" instead of "." to access package command hierarchy
```

```{r twitter}
tweepy<-import('tweepy')
screen_name<- 'Mooniac'
consumer_key <- 'XDA7AkpJKI5HEizun3k2BwSvs'
consumer_secret <- 'SnfxnlEt0CWTrKmt4hgZeQp0W6iqapMxlnBi5oimhf3qPcH6dy'
access_token <- '15399771-bD6OSgkLPf89XHP7XqqFw4jkq9Eaeluw0pmDWuN4W'
access_secret <- 'yDOuqQvLbWIH0Lafj1jYkUG9QD2DR7z1FGo9EpoRSIvfr'

create_token(
  app = "MooniacR",
  consumer_key = consumer_key,
  consumer_secret = consumer_secret,
  access_token = access_token,
  access_secret = access_secret)

# test: search for 100 tweets with #rstats 
rt <- search_tweets("#rstats", n = 100, include_rts = FALSE)
```

```{r py commands}
py_eval()	        # Run Python code
py_func()	        # Wrap an R function in a Python function with the same signature.
py_len()	        # Length of Python object
py_run_file()     # Run Python code
source_python()   # Read and evaluate a Python script
py_to_r()	        # Convert between Python and R objects
r_to_py()	        # Convert between R and Python objects
np_array()	      # NumPy array
py_set_seed()	    # Set Python and NumPy random seeds
```

