---
title: "mailR"
author: "John Van Camp"
date: "6/2/2018"
output: html_document
---
### mailR Examples
Not working with this version of mailR and Java
Need Java 8 (I'm using 10)
Or a new Java independent mailR

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
defl()
library(mailR)
gmailr::use_secret_file("/Users/John/Documents/R/DVC Class/rstatwork_mailr.json")
```

To send an email via a SMTP server that does not require authentication:
```{r}
send.mail(from = "sender@gmail.com",
          to = c("John <john@@van-camp.com>"),
          subject = "Subject of the email",
          body = "Body of the email",
          smtp = list(host.name = "aspmx.l.google.com", port = 25),
          authenticate = FALSE,
          send = TRUE)
```
Note that aspmx.l.google.com works for gmail recipients only. Check your gmail spam folder if using this server.

To send an email via a SMTP server that requires authentication:
```{r}
send.mail(from = "rstatswork@gmail.com",
          to = "john@van-camp.com",
          subject = "Subject of the email",
          body = "Body of the email",
          smtp = list(host.name = smtp$host.name, port = smtp$port, 
                      user.name = smtp$user.name, passwd = smtp$passwd, 
                      ssl = smtp$ssl),
          authenticate = TRUE,
          send = TRUE)
```

